[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

build_flags =
    -Wall
    -Wextra